from typing import Any, ClassVar

from typing import overload
import Boost.Python
EIGHTBITVALUE: DiscreteValueType
FOURBITVALUE: DiscreteValueType
ONEBITVALUE: DiscreteValueType
SIXTEENBITVALUE: DiscreteValueType
TWOBITVALUE: DiscreteValueType

class DiscreteValueType(Boost.Python.enum):
    EIGHTBITVALUE: ClassVar[DiscreteValueType] = ...
    FOURBITVALUE: ClassVar[DiscreteValueType] = ...
    ONEBITVALUE: ClassVar[DiscreteValueType] = ...
    SIXTEENBITVALUE: ClassVar[DiscreteValueType] = ...
    TWOBITVALUE: ClassVar[DiscreteValueType] = ...
    names: ClassVar[dict] = ...
    values: ClassVar[dict] = ...
    __slots__: ClassVar[tuple] = ...

class DiscreteValueVect(Boost.Python.instance):
    __instance_size__: ClassVar[int] = ...
    __safe_for_unpickling__: ClassVar[bool] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    @classmethod
    def GetTotalVal(cls, classRDKit) -> Any: ...
    @classmethod
    def GetValueType(cls, classRDKit) -> Any: ...
    @classmethod
    def __add__(cls, other) -> Any: ...
    @classmethod
    def __and__(cls, other) -> Any: ...
    @classmethod
    def __getinitargs__(cls, classRDKit) -> Any: ...
    @classmethod
    def __getitem__(cls, classRDKit, unsignedint) -> Any: ...
    @classmethod
    def __iadd__(cls, structboost, classRDKit) -> Any: ...
    @classmethod
    def __isub__(cls, structboost, classRDKit) -> Any: ...
    @classmethod
    def __len__(cls, classRDKit) -> Any: ...
    @classmethod
    def __or__(cls, other) -> Any: ...
    @classmethod
    def __reduce__(cls) -> Any: ...
    @classmethod
    def __setitem__(cls, index, object) -> Any: ...
    @classmethod
    def __sub__(cls, other) -> Any: ...

class ExplicitBitVect(Boost.Python.instance):
    __instance_size__: ClassVar[int] = ...
    __safe_for_unpickling__: ClassVar[bool] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    @classmethod
    def FromBase64(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def GetBit(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def GetNumBits(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def GetNumOffBits(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def GetNumOnBits(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def GetOnBits(cls, classExplicitBitVect) -> Any: ...
    @classmethod
    def SetBit(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def SetBitsFromList(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def ToBase64(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def ToBinary(cls, classExplicitBitVect) -> Any: ...
    @classmethod
    def ToBitString(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def ToList(cls, classExplicitBitVect) -> Any: ...
    @classmethod
    def UnSetBit(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def UnSetBitsFromList(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def __add__(cls, other) -> Any: ...
    @classmethod
    def __and__(cls, other) -> Any: ...
    @classmethod
    def __eq__(cls, other) -> Any: ...
    @classmethod
    def __getinitargs__(cls, classExplicitBitVect) -> Any: ...
    @classmethod
    def __getitem__(cls, classExplicitBitVect, int) -> Any: ...
    @classmethod
    def __iadd__(cls, structboost, classExplicitBitVect) -> Any: ...
    @classmethod
    def __invert__(cls) -> Any: ...
    @classmethod
    def __len__(cls) -> Any: ...
    @classmethod
    def __ne__(cls, other) -> Any: ...
    @classmethod
    def __or__(cls, other) -> Any: ...
    @classmethod
    def __reduce__(cls) -> Any: ...
    @classmethod
    def __setitem__(cls, index, object) -> Any: ...
    @classmethod
    def __xor__(cls, other) -> Any: ...

class FPBReader(Boost.Python.instance):
    __instance_size__: ClassVar[int] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    @classmethod
    def GetBytes(cls, classRDKit, unsignedint) -> Any: ...
    @classmethod
    def GetContainingNeighbors(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def GetFP(cls, classRDKit, unsignedint) -> Any: ...
    @classmethod
    def GetId(cls, classRDKit, unsignedint) -> Any: ...
    @classmethod
    def GetNumBits(cls, classRDKit) -> Any: ...
    @classmethod
    def GetTanimoto(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def GetTanimotoNeighbors(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def GetTversky(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def GetTverskyNeighbors(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def Init(cls, classRDKit) -> Any: ...
    @classmethod
    def __getitem__(cls, classRDKit, unsignedint) -> Any: ...
    @classmethod
    def __len__(cls, classRDKit) -> Any: ...
    @classmethod
    def __reduce__(cls) -> Any: ...

class IntSparseIntVect(Boost.Python.instance):
    __instance_size__: ClassVar[int] = ...
    __safe_for_unpickling__: ClassVar[bool] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    @classmethod
    def GetLength(cls, classRDKit) -> Any: ...
    @classmethod
    def GetNonzeroElements(cls, classRDKit) -> Any: ...
    @classmethod
    def GetTotalVal(cls, classRDKit) -> Any: ...
    @classmethod
    def ToBinary(cls, classRDKit) -> Any: ...
    @classmethod
    def ToList(cls, classRDKit) -> Any: ...
    @classmethod
    def UpdateFromSequence(cls, classRDKit, classboost) -> Any: ...
    @classmethod
    def __add__(cls, other) -> Any: ...
    @classmethod
    def __and__(cls, other) -> Any: ...
    @classmethod
    def __eq__(cls, other) -> Any: ...
    @classmethod
    def __getinitargs__(cls, classRDKit) -> Any: ...
    @classmethod
    def __getitem__(cls, classRDKit, int) -> Any: ...
    @overload
    @classmethod
    def __iadd__(cls, structboost, classRDKit) -> Any: ...
    @overload
    @classmethod
    def __iadd__(cls, structboost, int) -> Any: ...
    @classmethod
    def __idiv__(cls, structboost, int) -> Any: ...
    @classmethod
    def __imul__(cls, structboost, int) -> Any: ...
    @overload
    @classmethod
    def __isub__(cls, structboost, classRDKit) -> Any: ...
    @overload
    @classmethod
    def __isub__(cls, structboost, int) -> Any: ...
    @classmethod
    def __ne__(cls, other) -> Any: ...
    @classmethod
    def __or__(cls, other) -> Any: ...
    @classmethod
    def __reduce__(cls) -> Any: ...
    @classmethod
    def __setitem__(cls, index, object) -> Any: ...
    @classmethod
    def __sub__(cls, other) -> Any: ...

class LongSparseIntVect(Boost.Python.instance):
    __instance_size__: ClassVar[int] = ...
    __safe_for_unpickling__: ClassVar[bool] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    @classmethod
    def GetLength(cls, classRDKit) -> Any: ...
    @classmethod
    def GetNonzeroElements(cls, classRDKit) -> Any: ...
    @classmethod
    def GetTotalVal(cls, classRDKit) -> Any: ...
    @classmethod
    def ToBinary(cls, classRDKit) -> Any: ...
    @classmethod
    def ToList(cls, classRDKit) -> Any: ...
    @classmethod
    def UpdateFromSequence(cls, classRDKit, classboost) -> Any: ...
    @classmethod
    def __add__(cls, other) -> Any: ...
    @classmethod
    def __and__(cls, other) -> Any: ...
    @classmethod
    def __eq__(cls, other) -> Any: ...
    @classmethod
    def __getinitargs__(cls, classRDKit) -> Any: ...
    @classmethod
    def __getitem__(cls, classRDKit, __int64) -> Any: ...
    @overload
    @classmethod
    def __iadd__(cls, structboost, classRDKit) -> Any: ...
    @overload
    @classmethod
    def __iadd__(cls, structboost, int) -> Any: ...
    @classmethod
    def __idiv__(cls, structboost, int) -> Any: ...
    @classmethod
    def __imul__(cls, structboost, int) -> Any: ...
    @overload
    @classmethod
    def __isub__(cls, structboost, classRDKit) -> Any: ...
    @overload
    @classmethod
    def __isub__(cls, structboost, int) -> Any: ...
    @classmethod
    def __ne__(cls, other) -> Any: ...
    @classmethod
    def __or__(cls, other) -> Any: ...
    @classmethod
    def __reduce__(cls) -> Any: ...
    @classmethod
    def __setitem__(cls, classRDKit, __int64, int) -> Any: ...
    @classmethod
    def __sub__(cls, other) -> Any: ...

class MultiFPBReader(Boost.Python.instance):
    __instance_size__: ClassVar[int] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    @classmethod
    def AddReader(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def GetContainingNeighbors(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def GetNumBits(cls, classRDKit) -> Any: ...
    @classmethod
    def GetReader(cls, classRDKit, unsignedint) -> Any: ...
    @classmethod
    def GetTanimotoNeighbors(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def GetTverskyNeighbors(cls, *args, **kwargs) -> Any: ...
    @overload
    @classmethod
    def Init(cls) -> Any: ...
    @overload
    @classmethod
    def Init(cls, classRDKit) -> Any: ...
    @classmethod
    def __len__(cls, classRDKit) -> Any: ...
    @classmethod
    def __reduce__(cls) -> Any: ...

class SparseBitVect(Boost.Python.instance):
    __instance_size__: ClassVar[int] = ...
    __safe_for_unpickling__: ClassVar[bool] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    @classmethod
    def FromBase64(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def GetBit(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def GetNumBits(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def GetNumOffBits(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def GetNumOnBits(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def GetOnBits(cls, classSparseBitVect) -> Any: ...
    @classmethod
    def SetBit(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def SetBitsFromList(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def ToBase64(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def ToBinary(cls, classSparseBitVect) -> Any: ...
    @classmethod
    def ToBitString(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def ToList(cls, classSparseBitVect) -> Any: ...
    @classmethod
    def UnSetBit(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def UnSetBitsFromList(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def __and__(cls, other) -> Any: ...
    @classmethod
    def __eq__(cls, other) -> Any: ...
    @classmethod
    def __getinitargs__(cls, classSparseBitVect) -> Any: ...
    @classmethod
    def __getitem__(cls, classSparseBitVect, int) -> Any: ...
    @classmethod
    def __invert__(cls) -> Any: ...
    @classmethod
    def __len__(cls) -> Any: ...
    @classmethod
    def __ne__(cls, other) -> Any: ...
    @classmethod
    def __or__(cls, other) -> Any: ...
    @classmethod
    def __reduce__(cls) -> Any: ...
    @classmethod
    def __setitem__(cls, index, object) -> Any: ...
    @classmethod
    def __xor__(cls, other) -> Any: ...

class UIntSparseIntVect(Boost.Python.instance):
    __instance_size__: ClassVar[int] = ...
    __safe_for_unpickling__: ClassVar[bool] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    @classmethod
    def GetLength(cls, classRDKit) -> Any: ...
    @classmethod
    def GetNonzeroElements(cls, classRDKit) -> Any: ...
    @classmethod
    def GetTotalVal(cls, classRDKit) -> Any: ...
    @classmethod
    def ToBinary(cls, classRDKit) -> Any: ...
    @classmethod
    def ToList(cls, classRDKit) -> Any: ...
    @classmethod
    def UpdateFromSequence(cls, classRDKit, classboost) -> Any: ...
    @classmethod
    def __add__(cls, other) -> Any: ...
    @classmethod
    def __and__(cls, other) -> Any: ...
    @classmethod
    def __eq__(cls, other) -> Any: ...
    @classmethod
    def __getinitargs__(cls, classRDKit) -> Any: ...
    @classmethod
    def __getitem__(cls, classRDKit, unsignedint) -> Any: ...
    @overload
    @classmethod
    def __iadd__(cls, structboost, classRDKit) -> Any: ...
    @overload
    @classmethod
    def __iadd__(cls, structboost, int) -> Any: ...
    @classmethod
    def __idiv__(cls, structboost, int) -> Any: ...
    @classmethod
    def __imul__(cls, structboost, int) -> Any: ...
    @overload
    @classmethod
    def __isub__(cls, structboost, classRDKit) -> Any: ...
    @overload
    @classmethod
    def __isub__(cls, structboost, int) -> Any: ...
    @classmethod
    def __ne__(cls, other) -> Any: ...
    @classmethod
    def __or__(cls, other) -> Any: ...
    @classmethod
    def __reduce__(cls) -> Any: ...
    @classmethod
    def __setitem__(cls, classRDKit, unsignedint, int) -> Any: ...
    @classmethod
    def __sub__(cls, other) -> Any: ...

class ULongSparseIntVect(Boost.Python.instance):
    __instance_size__: ClassVar[int] = ...
    __safe_for_unpickling__: ClassVar[bool] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    @classmethod
    def GetLength(cls, classRDKit) -> Any: ...
    @classmethod
    def GetNonzeroElements(cls, classRDKit) -> Any: ...
    @classmethod
    def GetTotalVal(cls, classRDKit) -> Any: ...
    @classmethod
    def ToBinary(cls, classRDKit) -> Any: ...
    @classmethod
    def ToList(cls, classRDKit) -> Any: ...
    @classmethod
    def UpdateFromSequence(cls, classRDKit, classboost) -> Any: ...
    @classmethod
    def __add__(cls, other) -> Any: ...
    @classmethod
    def __and__(cls, other) -> Any: ...
    @classmethod
    def __eq__(cls, other) -> Any: ...
    @classmethod
    def __getinitargs__(cls, classRDKit) -> Any: ...
    @classmethod
    def __getitem__(cls, classRDKit, unsigned__int64) -> Any: ...
    @overload
    @classmethod
    def __iadd__(cls, structboost, classRDKit) -> Any: ...
    @overload
    @classmethod
    def __iadd__(cls, structboost, int) -> Any: ...
    @classmethod
    def __idiv__(cls, structboost, int) -> Any: ...
    @classmethod
    def __imul__(cls, structboost, int) -> Any: ...
    @overload
    @classmethod
    def __isub__(cls, structboost, classRDKit) -> Any: ...
    @overload
    @classmethod
    def __isub__(cls, structboost, int) -> Any: ...
    @classmethod
    def __ne__(cls, other) -> Any: ...
    @classmethod
    def __or__(cls, other) -> Any: ...
    @classmethod
    def __reduce__(cls) -> Any: ...
    @classmethod
    def __setitem__(cls, classRDKit, unsigned__int64, int) -> Any: ...
    @classmethod
    def __sub__(cls, other) -> Any: ...

def AllBitSimilarity(*args, **kwargs) -> Any: ...
def AllProbeBitsMatch(*args, **kwargs) -> Any: ...
def AsymmetricSimilarity(*args, **kwargs) -> Any: ...
def AsymmetricSimilarityNeighbors(*args, **kwargs) -> Any: ...
def AsymmetricSimilarityNeighbors_sparse(*args, **kwargs) -> Any: ...
@overload
def BitVectToBinaryText(classSparseBitVect) -> Any: ...
@overload
def BitVectToBinaryText(classExplicitBitVect) -> Any: ...
@overload
def BitVectToFPSText(classSparseBitVect) -> Any: ...
@overload
def BitVectToFPSText(classExplicitBitVect) -> Any: ...
@overload
def BitVectToText(classSparseBitVect) -> Any: ...
@overload
def BitVectToText(classExplicitBitVect) -> Any: ...
def BraunBlanquetSimilarity(*args, **kwargs) -> Any: ...
def BraunBlanquetSimilarityNeighbors(*args, **kwargs) -> Any: ...
def BraunBlanquetSimilarityNeighbors_sparse(*args, **kwargs) -> Any: ...
def BulkAllBitSimilarity(*args, **kwargs) -> Any: ...
def BulkAsymmetricSimilarity(*args, **kwargs) -> Any: ...
def BulkBraunBlanquetSimilarity(*args, **kwargs) -> Any: ...
def BulkCosineSimilarity(*args, **kwargs) -> Any: ...
@overload
def BulkDiceSimilarity(classRDKit, classboost) -> Any: ...
@overload
def BulkDiceSimilarity(classRDKit, classboost) -> Any: ...
@overload
def BulkDiceSimilarity(classRDKit, classboost) -> Any: ...
@overload
def BulkDiceSimilarity(classRDKit, classboost) -> Any: ...
def BulkKulczynskiSimilarity(*args, **kwargs) -> Any: ...
def BulkMcConnaugheySimilarity(*args, **kwargs) -> Any: ...
def BulkOnBitSimilarity(*args, **kwargs) -> Any: ...
def BulkRogotGoldbergSimilarity(*args, **kwargs) -> Any: ...
def BulkRusselSimilarity(*args, **kwargs) -> Any: ...
def BulkSokalSimilarity(*args, **kwargs) -> Any: ...
@overload
def BulkTanimotoSimilarity(classRDKit, classboost) -> Any: ...
@overload
def BulkTanimotoSimilarity(classRDKit, classboost) -> Any: ...
@overload
def BulkTanimotoSimilarity(classRDKit, classboost) -> Any: ...
@overload
def BulkTanimotoSimilarity(classRDKit, classboost) -> Any: ...
def BulkTverskySimilarity(*args, **kwargs) -> Any: ...
def ComputeL1Norm(*args, **kwargs) -> Any: ...
def ConvertToExplicit(*args, **kwargs) -> Any: ...
@overload
def ConvertToNumpyArray(classExplicitBitVect, classboost) -> Any: ...
@overload
def ConvertToNumpyArray(classRDKit, classboost) -> Any: ...
@overload
def ConvertToNumpyArray(classRDKit, classboost) -> Any: ...
@overload
def ConvertToNumpyArray(classRDKit, classboost) -> Any: ...
@overload
def ConvertToNumpyArray(classRDKit, classboost) -> Any: ...
@overload
def ConvertToNumpyArray(classRDKit, classboost) -> Any: ...
def CosineSimilarity(*args, **kwargs) -> Any: ...
def CosineSimilarityNeighbors(*args, **kwargs) -> Any: ...
def CosineSimilarityNeighbors_sparse(*args, **kwargs) -> Any: ...
def CreateFromBinaryText(*args, **kwargs) -> Any: ...
def CreateFromBitString(*args, **kwargs) -> Any: ...
def CreateFromFPSText(*args, **kwargs) -> Any: ...
def DiceSimilarity(*args, **kwargs) -> Any: ...
def DiceSimilarityNeighbors(*args, **kwargs) -> Any: ...
def DiceSimilarityNeighbors_sparse(*args, **kwargs) -> Any: ...
def FoldFingerprint(*args, **kwargs) -> Any: ...
def InitFromDaylightString(*args, **kwargs) -> Any: ...
def KulczynskiSimilarity(*args, **kwargs) -> Any: ...
def KulczynskiSimilarityNeighbors(*args, **kwargs) -> Any: ...
def KulczynskiSimilarityNeighbors_sparse(*args, **kwargs) -> Any: ...
def McConnaugheySimilarity(*args, **kwargs) -> Any: ...
def McConnaugheySimilarityNeighbors(*args, **kwargs) -> Any: ...
def McConnaugheySimilarityNeighbors_sparse(*args, **kwargs) -> Any: ...
def NumBitsInCommon(*args, **kwargs) -> Any: ...
def OffBitProjSimilarity(*args, **kwargs) -> Any: ...
def OffBitsInCommon(*args, **kwargs) -> Any: ...
def OnBitProjSimilarity(*args, **kwargs) -> Any: ...
def OnBitSimilarity(*args, **kwargs) -> Any: ...
def OnBitsInCommon(*args, **kwargs) -> Any: ...
def RogotGoldbergSimilarity(*args, **kwargs) -> Any: ...
def RogotGoldbergSimilarityNeighbors(*args, **kwargs) -> Any: ...
def RogotGoldbergSimilarityNeighbors_sparse(*args, **kwargs) -> Any: ...
def RusselSimilarity(*args, **kwargs) -> Any: ...
def RusselSimilarityNeighbors(*args, **kwargs) -> Any: ...
def RusselSimilarityNeighbors_sparse(*args, **kwargs) -> Any: ...
def SokalSimilarity(*args, **kwargs) -> Any: ...
def SokalSimilarityNeighbors(*args, **kwargs) -> Any: ...
def SokalSimilarityNeighbors_sparse(*args, **kwargs) -> Any: ...
def TanimotoSimilarity(*args, **kwargs) -> Any: ...
def TanimotoSimilarityNeighbors(*args, **kwargs) -> Any: ...
def TanimotoSimilarityNeighbors_sparse(*args, **kwargs) -> Any: ...
def TverskySimilarity(*args, **kwargs) -> Any: ...
