from typing import Any, ClassVar

import Boost.Python

class Point2D(Boost.Python.instance):
    __instance_size__: ClassVar[int] = ...
    __safe_for_unpickling__: ClassVar[bool] = ...
    x: Any
    y: Any
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    @classmethod
    def AngleTo(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def DirectionVector(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def DotProduct(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def Length(cls, classRDGeom) -> Any: ...
    @classmethod
    def LengthSq(cls, classRDGeom) -> Any: ...
    @classmethod
    def Normalize(cls, classRDGeom) -> Any: ...
    @classmethod
    def SignedAngleTo(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def __add__(cls, other) -> Any: ...
    @classmethod
    def __getinitargs__(cls, classRDGeom) -> Any: ...
    @classmethod
    def __getitem__(cls, classRDGeom, int) -> Any: ...
    @classmethod
    def __iadd__(cls, structboost, classRDGeom) -> Any: ...
    @classmethod
    def __idiv__(cls, classRDGeom, double) -> Any: ...
    @classmethod
    def __imul__(cls, classRDGeom, double) -> Any: ...
    @classmethod
    def __isub__(cls, structboost, classRDGeom) -> Any: ...
    @classmethod
    def __len__(cls, classRDGeom) -> Any: ...
    @classmethod
    def __mul__(cls, classRDGeom, double) -> Any: ...
    @classmethod
    def __reduce__(cls) -> Any: ...
    @classmethod
    def __sub__(cls, other) -> Any: ...
    @classmethod
    def __truediv__(cls, classRDGeom, double) -> Any: ...

class Point3D(Boost.Python.instance):
    __instance_size__: ClassVar[int] = ...
    __safe_for_unpickling__: ClassVar[bool] = ...
    x: Any
    y: Any
    z: Any
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    @classmethod
    def AngleTo(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def CrossProduct(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def DirectionVector(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def Distance(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def DotProduct(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def Length(cls, classRDGeom) -> Any: ...
    @classmethod
    def LengthSq(cls, classRDGeom) -> Any: ...
    @classmethod
    def Normalize(cls, classRDGeom) -> Any: ...
    @classmethod
    def SignedAngleTo(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def __add__(cls, other) -> Any: ...
    @classmethod
    def __getinitargs__(cls, classRDGeom) -> Any: ...
    @classmethod
    def __getitem__(cls, classRDGeom, int) -> Any: ...
    @classmethod
    def __iadd__(cls, structboost, classRDGeom) -> Any: ...
    @classmethod
    def __idiv__(cls, classRDGeom, double) -> Any: ...
    @classmethod
    def __imul__(cls, classRDGeom, double) -> Any: ...
    @classmethod
    def __isub__(cls, structboost, classRDGeom) -> Any: ...
    @classmethod
    def __len__(cls, classRDGeom) -> Any: ...
    @classmethod
    def __mul__(cls, classRDGeom, double) -> Any: ...
    @classmethod
    def __reduce__(cls) -> Any: ...
    @classmethod
    def __sub__(cls, other) -> Any: ...
    @classmethod
    def __truediv__(cls, classRDGeom, double) -> Any: ...

class PointND(Boost.Python.instance):
    __instance_size__: ClassVar[int] = ...
    __safe_for_unpickling__: ClassVar[bool] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    @classmethod
    def AngleTo(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def DirectionVector(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def Distance(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def DotProduct(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def Length(cls, classRDGeom) -> Any: ...
    @classmethod
    def LengthSq(cls, classRDGeom) -> Any: ...
    @classmethod
    def Normalize(cls, classRDGeom) -> Any: ...
    @classmethod
    def __add__(cls, other) -> Any: ...
    @classmethod
    def __getinitargs__(cls, classRDGeom) -> Any: ...
    @classmethod
    def __getitem__(cls, classRDGeom, int) -> Any: ...
    @classmethod
    def __getstate__(cls, classRDGeom) -> Any: ...
    @classmethod
    def __iadd__(cls, structboost, classRDGeom) -> Any: ...
    @classmethod
    def __idiv__(cls, classRDGeom, double) -> Any: ...
    @classmethod
    def __imul__(cls, classRDGeom, double) -> Any: ...
    @classmethod
    def __isub__(cls, structboost, classRDGeom) -> Any: ...
    @classmethod
    def __len__(cls, classRDGeom) -> Any: ...
    @classmethod
    def __mul__(cls, classRDGeom, double) -> Any: ...
    @classmethod
    def __reduce__(cls) -> Any: ...
    @classmethod
    def __setitem__(cls, classRDGeom, int, double) -> Any: ...
    @classmethod
    def __setstate__(cls, classRDGeom, classboost) -> Any: ...
    @classmethod
    def __sub__(cls, other) -> Any: ...
    @classmethod
    def __truediv__(cls, classRDGeom, double) -> Any: ...

class UniformGrid3D_(Boost.Python.instance):
    __instance_size__: ClassVar[int] = ...
    __safe_for_unpickling__: ClassVar[bool] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    @classmethod
    def CompareParams(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def GetGridIndex(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def GetGridIndices(cls, classRDGeom, unsignedint) -> Any: ...
    @classmethod
    def GetGridPointIndex(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def GetGridPointLoc(cls, classRDGeom, unsignedint) -> Any: ...
    @classmethod
    def GetNumX(cls, classRDGeom) -> Any: ...
    @classmethod
    def GetNumY(cls, classRDGeom) -> Any: ...
    @classmethod
    def GetNumZ(cls, classRDGeom) -> Any: ...
    @classmethod
    def GetOccupancyVect(cls, classRDGeom) -> Any: ...
    @classmethod
    def GetOffset(cls, classRDGeom) -> Any: ...
    @classmethod
    def GetSize(cls, classRDGeom) -> Any: ...
    @classmethod
    def GetSpacing(cls, classRDGeom) -> Any: ...
    @classmethod
    def GetVal(cls, classRDGeom, unsignedint) -> Any: ...
    @classmethod
    def GetValPoint(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def SetSphereOccupancy(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def SetVal(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def SetValPoint(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def __getinitargs__(cls, classRDGeom) -> Any: ...
    @classmethod
    def __iadd__(cls, structboost, classRDGeom) -> Any: ...
    @classmethod
    def __iand__(cls, structboost, classRDGeom) -> Any: ...
    @classmethod
    def __ior__(cls, structboost, classRDGeom) -> Any: ...
    @classmethod
    def __isub__(cls, structboost, classRDGeom) -> Any: ...
    @classmethod
    def __reduce__(cls) -> Any: ...

def ComputeDihedralAngle(*args, **kwargs) -> Any: ...
def ComputeGridCentroid(*args, **kwargs) -> Any: ...
def ComputeSignedDihedralAngle(*args, **kwargs) -> Any: ...
def FindGridTerminalPoints(*args, **kwargs) -> Any: ...
def ProtrudeDistance(*args, **kwargs) -> Any: ...
def TanimotoDistance(*args, **kwargs) -> Any: ...
def TverskyIndex(*args, **kwargs) -> Any: ...
def UniformGrid3D(*args, **kwargs) -> Any: ...
def WriteGridToFile(*args, **kwargs) -> Any: ...
