[tool.poetry]
name = "substances-aws-queue"
version = "0.1.0"
description = ""
authors = ["Luidgi Gromat <gromat.luidgi@gmail.com>"]
readme = "README.md"
packages = [
    {include = "substances_aws_queue"}, {include= "substances_aws_queue/py.typed"}
]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"
boto3 = "^1.26.39"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
