[tool.poetry]
name = "substances-rabbitmq"
version = "0.1.0"
description = ""
authors = ["Luidgi Gromat <gromat.luidgi@gmail.com>"]
readme = "README.md"
packages = [
    {include = "substances_rabbitmq"}, {include = "substances_rabbitmq/py.typed"}
]

[tool.poetry.dependencies]
python = "^3.9"
jsonpickle = "^3.0.0"
pika = "^1.3.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
