# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import sync_pb2 as sync__pb2


class SyncsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListSyncs = channel.unary_unary(
                '/syncs.Syncs/ListSyncs',
                request_serializer=sync__pb2.ListRequest.SerializeToString,
                response_deserializer=sync__pb2.ListResponse.FromString,
                )
        self.GetSync = channel.unary_unary(
                '/syncs.Syncs/GetSync',
                request_serializer=sync__pb2.GetRequest.SerializeToString,
                response_deserializer=sync__pb2.ItemResponse.FromString,
                )


class SyncsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListSyncs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSync(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SyncsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListSyncs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSyncs,
                    request_deserializer=sync__pb2.ListRequest.FromString,
                    response_serializer=sync__pb2.ListResponse.SerializeToString,
            ),
            'GetSync': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSync,
                    request_deserializer=sync__pb2.GetRequest.FromString,
                    response_serializer=sync__pb2.ItemResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'syncs.Syncs', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Syncs(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListSyncs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/syncs.Syncs/ListSyncs',
            sync__pb2.ListRequest.SerializeToString,
            sync__pb2.ListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/syncs.Syncs/GetSync',
            sync__pb2.GetRequest.SerializeToString,
            sync__pb2.ItemResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
