from rdkit import Chem as Chem
from rdkit.VLib.Supply import SupplyNode as SupplyNode

class SDSupplyNode(SupplyNode):
    def __init__(self, fileName, **kwargs) -> None: ...
    def reset(self) -> None: ...
    def next(self): ...
