from rdkit import Chem as Chem
from rdkit.VLib.Supply import SupplyNode as SupplyNode

class SmilesSupplyNode(SupplyNode):
    def __init__(self, fileName, delim: str = ..., nameColumn: int = ..., smilesColumn: int = ..., titleLine: int = ..., **kwargs) -> None: ...
    def reset(self) -> None: ...
    def next(self): ...
