from rdkit import Chem as Chem
from rdkit.VLib.Filter import FilterNode as FilterNode

class DupeFilter(FilterNode):
    def __init__(self, **kwargs) -> None: ...
    def reset(self) -> None: ...
    def filter(self, cmpd): ...
