from rdkit.Chem.rdfiltercatalog import *
from _typeshed import Incomplete
from rdkit import Chem as Chem

class FilterMatcher(PythonFilterMatcher):
    name: Incomplete
    def __init__(self, name: str = ...) -> None: ...
    def HasMatch(self, mol) -> None: ...
    def GetMatches(self, mol, matchVect): ...
    def IsValid(self, mol) -> None: ...
    def GetName(self): ...
