from rdkit import Chem as Chem

class FragmentMatcher:
    def __init__(self) -> None: ...
    def AddExclusion(self, sma) -> None: ...
    def Init(self, sma) -> None: ...
    def GetSMARTS(self) -> None: ...
    def GetExclusionSMARTS(self) -> None: ...
    def HasMatch(self, mol): ...
    def GetMatch(self, mol): ...
    def GetMatches(self, mol, uniquify: int = ...): ...
    def GetBond(self, idx): ...
