from _typeshed import Incomplete
from rdkit.Chem import Mol as Mol

log: Incomplete
RDK_MOLS_AS_IMAGE_ATTR: str
InteractiveRenderer: Incomplete
PrintAsImageString: Incomplete
molJustify: Incomplete
pandas_frame: Incomplete
pandas_formats: Incomplete
to_html_class: Incomplete
orig_get_adjustment: Incomplete
adj: Incomplete
html_formatter_module: Incomplete
html_formatter_class: Incomplete
orig_write_cell: Incomplete
orig_to_html: Incomplete
pprint_thing: Incomplete

def is_molecule_image(s): ...

styleRegex: Incomplete

class MolFormatter:
    orig_formatter: Incomplete
    def __init__(self, orig_formatter: Incomplete | None = ...) -> None: ...
    @staticmethod
    def default_formatter(x): ...
    @staticmethod
    def is_mol(x): ...
    @classmethod
    def get_formatters(cls, df, orig_formatters): ...
    def __call__(self, x): ...

def check_rdk_attr(frame, attr): ...
def set_rdk_attr(frame, attr) -> None: ...
def patched_to_html(self, *args, **kwargs): ...
def patched_write_cell(self, s, *args, **kwargs): ...
def patched_get_adjustment(): ...
def renderImagesInAllDataFrames(images: bool = ...) -> None: ...
def changeMoleculeRendering(frame, renderer: str = ...) -> None: ...
def patchPandas() -> None: ...
def unpatchPandas() -> None: ...
