from _typeshed import Incomplete
from rdkit import Chem as Chem, DataStructs as DataStructs
from rdkit.Chem import AllChem as AllChem, Draw as Draw, PandasPatcher as PandasPatcher, SDWriter as SDWriter, rdchem as rdchem
from rdkit.Chem.Draw.IPythonConsole import InteractiveRenderer as InteractiveRenderer, drawOptions as drawOptions
from rdkit.Chem.Scaffolds import MurckoScaffold as MurckoScaffold

InteractiveRenderer: Incomplete
drawOptions: Incomplete
log: Incomplete
highlightSubstructures: bool
molRepresentation: str
molSize: Incomplete
molJustify: str

def PrintAsBase64PNGString(x): ...
def PrintAsImageString(x): ...
def RenderImagesInAllDataFrames(images: bool = ...) -> None: ...
def LoadSDF(filename, idName: str = ..., molColName: str = ..., includeFingerprints: bool = ..., isomericSmiles: bool = ..., smilesName: Incomplete | None = ..., embedProps: bool = ..., removeHs: bool = ..., strictParsing: bool = ...): ...
def RGroupDecompositionToFrame(groups, mols, include_core: bool = ..., redraw_sidechains: bool = ...): ...
def AddMoleculeColumnToFrame(frame, smilesCol: str = ..., molCol: str = ..., includeFingerprints: bool = ...): ...
def ChangeMoleculeRendering(frame: Incomplete | None = ..., renderer: str = ...) -> None: ...
def WriteSDF(df, out, molColName: str = ..., idName: Incomplete | None = ..., properties: Incomplete | None = ..., allNumeric: bool = ...) -> None: ...
def RemoveSaltsFromFrame(frame, molCol: str = ...): ...
def SaveSMILESFromFrame(frame, outFile, molCol: str = ..., NamesCol: str = ..., isomericSmiles: bool = ...) -> None: ...
def SaveXlsxFromFrame(frame, outFile, molCol: str = ..., size=...) -> None: ...
def FrameToGridImage(frame, column: str = ..., legendsCol: Incomplete | None = ..., **kwargs): ...
def AddMurckoToFrame(frame, molCol: str = ..., MurckoCol: str = ..., Generic: bool = ...): ...
def AlignMol(mol, scaffold): ...
def AlignToScaffold(frame, molCol: str = ..., scaffoldCol: str = ...): ...
def InstallPandasTools() -> None: ...
def UninstallPandasTools() -> None: ...
