from typing import Any, ClassVar

import Boost.Python

class CoordGenParams(Boost.Python.instance):
    __instance_size__: ClassVar[int] = ...
    coordgenScaling: Any
    dbg_useConstrained: Any
    dbg_useFixed: Any
    minimizerPrecision: Any
    templateFileDir: Any
    treatNonterminalBondsToMetalAsZOBs: Any
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    @classmethod
    def SetCoordMap(cls, structRDKit, classboost) -> Any: ...
    @classmethod
    def SetTemplateMol(cls, structRDKit, classRDKit) -> Any: ...
    @classmethod
    def __reduce__(cls) -> Any: ...
    @property
    def sketcherBestPrecision(self) -> Any: ...
    @property
    def sketcherCoarsePrecision(self) -> Any: ...
    @property
    def sketcherQuickPrecision(self) -> Any: ...
    @property
    def sketcherStandardPrecision(self) -> Any: ...

def AddCoords(classRDKit) -> Any: ...
def SetDefaultTemplateFileDir(*args, **kwargs) -> Any: ...
