from typing import Any

def Compute2DCoords(classRDKit) -> Any: ...
def Compute2DCoordsMimicDistmat(classRDKit, classboost) -> Any: ...
def GenerateDepictionMatching2DStructure(*args, **kwargs) -> Any: ...
def GenerateDepictionMatching3DStructure(*args, **kwargs) -> Any: ...
def NormalizeDepiction(classRDKit) -> Any: ...
def SetPreferCoordGen(bool) -> Any: ...
def StraightenDepiction(classRDKit) -> Any: ...
