from typing import Any

import Boost.Python

class EHTResults(Boost.Python.instance):
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    @classmethod
    def GetAtomicCharges(cls, structRDKit) -> Any: ...
    @classmethod
    def GetHamiltonian(cls, structRDKit) -> Any: ...
    @classmethod
    def GetOrbitalEnergies(cls, structRDKit) -> Any: ...
    @classmethod
    def GetOverlapMatrix(cls, structRDKit) -> Any: ...
    @classmethod
    def GetReducedChargeMatrix(cls, structRDKit) -> Any: ...
    @classmethod
    def GetReducedOverlapPopulationMatrix(cls, structRDKit) -> Any: ...
    @classmethod
    def __reduce__(cls) -> Any: ...
    @property
    def fermiEnergy(self) -> Any: ...
    @property
    def numElectrons(self) -> Any: ...
    @property
    def numOrbitals(self) -> Any: ...
    @property
    def totalEnergy(self) -> Any: ...

def RunMol(classRDKit) -> Any: ...
