from typing import Any

def GetUFFAngleBendParams(*args, **kwargs) -> Any: ...
def GetUFFBondStretchParams(*args, **kwargs) -> Any: ...
def GetUFFInversionParams(*args, **kwargs) -> Any: ...
def GetUFFTorsionParams(*args, **kwargs) -> Any: ...
def GetUFFVdWParams(*args, **kwargs) -> Any: ...
def MMFFGetMoleculeForceField(classRDKit, classForceFields) -> Any: ...
def MMFFGetMoleculeProperties(classRDKit) -> Any: ...
def MMFFHasAllMoleculeParams(classRDKit) -> Any: ...
def MMFFOptimizeMolecule(classRDKit) -> Any: ...
def MMFFOptimizeMoleculeConfs(classRDKit) -> Any: ...
def MMFFSanitizeMolecule(classRDKit) -> Any: ...
def OptimizeMolecule(classForceFields) -> Any: ...
def OptimizeMoleculeConfs(classRDKit, classForceFields) -> Any: ...
def UFFGetMoleculeForceField(classRDKit) -> Any: ...
def UFFHasAllMoleculeParams(classRDKit) -> Any: ...
def UFFOptimizeMolecule(classRDKit) -> Any: ...
def UFFOptimizeMoleculeConfs(classRDKit) -> Any: ...
