from typing import Any, ClassVar

import Boost.Python
APolar: SASAClass
LeeRichards: SASAAlgorithm
NACCESS: SASAClassifier
OONS: SASAClassifier
Polar: SASAClass
Protor: SASAClassifier
ShrakeRupley: SASAAlgorithm
Unclassified: SASAClass

class SASAAlgorithm(Boost.Python.enum):
    LeeRichards: ClassVar[SASAAlgorithm] = ...
    ShrakeRupley: ClassVar[SASAAlgorithm] = ...
    names: ClassVar[dict] = ...
    values: ClassVar[dict] = ...
    __slots__: ClassVar[tuple] = ...

class SASAClass(Boost.Python.enum):
    APolar: ClassVar[SASAClass] = ...
    Polar: ClassVar[SASAClass] = ...
    Unclassified: ClassVar[SASAClass] = ...
    names: ClassVar[dict] = ...
    values: ClassVar[dict] = ...
    __slots__: ClassVar[tuple] = ...

class SASAClassifier(Boost.Python.enum):
    NACCESS: ClassVar[SASAClassifier] = ...
    OONS: ClassVar[SASAClassifier] = ...
    Protor: ClassVar[SASAClassifier] = ...
    names: ClassVar[dict] = ...
    values: ClassVar[dict] = ...
    __slots__: ClassVar[tuple] = ...

class SASAOpts(Boost.Python.instance):
    __instance_size__: ClassVar[int] = ...
    algorithm: Any
    classifier: Any
    probeRadius: Any
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    @classmethod
    def __reduce__(cls) -> Any: ...

def CalcSASA(classRDKit, classboost) -> Any: ...
def MakeFreeSasaAPolarAtomQuery() -> Any: ...
def MakeFreeSasaPolarAtomQuery() -> Any: ...
def classifyAtoms(classRDKit) -> Any: ...
