from typing import Any, ClassVar

import Boost.Python

class MHFPEncoder(Boost.Python.instance):
    __instance_size__: ClassVar[int] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    @classmethod
    def CreateShinglingFromMol(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def CreateShinglingFromSmiles(cls, *args, **kwargs) -> Any: ...
    def Distance(self, *args, **kwargs) -> Any: ...
    @classmethod
    def EncodeMol(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def EncodeMolsBulk(cls, classRDKit, classboost) -> Any: ...
    @classmethod
    def EncodeSECFPMol(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def EncodeSECFPMolsBulk(cls, classRDKit, classboost) -> Any: ...
    @classmethod
    def EncodeSECFPSmiles(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def EncodeSECFPSmilesBulk(cls, classRDKit, classboost) -> Any: ...
    @classmethod
    def EncodeSmiles(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def EncodeSmilesBulk(cls, classRDKit, classboost) -> Any: ...
    @classmethod
    def FromArray(cls, classRDKit, classboost) -> Any: ...
    @classmethod
    def FromStringArray(cls, classRDKit, classboost) -> Any: ...
    @classmethod
    def __reduce__(cls) -> Any: ...
