from typing import Any

import Boost.Python

class O3A(Boost.Python.instance):
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    @classmethod
    def Align(cls, classRDKit) -> Any: ...
    @classmethod
    def Matches(cls, classRDKit) -> Any: ...
    @classmethod
    def Score(cls, classRDKit) -> Any: ...
    @classmethod
    def Trans(cls, classRDKit) -> Any: ...
    @classmethod
    def Weights(cls, classRDKit) -> Any: ...
    @classmethod
    def __reduce__(cls) -> Any: ...

def AlignMol(*args, **kwargs) -> Any: ...
def AlignMolConformers(*args, **kwargs) -> Any: ...
def CalcRMS(*args, **kwargs) -> Any: ...
def GetAlignmentTransform(*args, **kwargs) -> Any: ...
def GetBestAlignmentTransform(*args, **kwargs) -> Any: ...
def GetBestRMS(*args, **kwargs) -> Any: ...
def GetCrippenO3A(*args, **kwargs) -> Any: ...
def GetCrippenO3AForProbeConfs(*args, **kwargs) -> Any: ...
def GetO3A(*args, **kwargs) -> Any: ...
def GetO3AForProbeConfs(*args, **kwargs) -> Any: ...
def RandomTransform(classRDKit) -> Any: ...
