from typing import Any, ClassVar

from typing import overload
import Boost.Python

class MolChemicalFeature(Boost.Python.instance):
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    @classmethod
    def ClearCache(cls, classRDKit) -> Any: ...
    @classmethod
    def GetActiveConformer(cls, classRDKit) -> Any: ...
    @classmethod
    def GetAtomIds(cls, classRDKit) -> Any: ...
    @classmethod
    def GetFactory(cls, classRDKit) -> Any: ...
    @classmethod
    def GetFamily(cls, classRDKit) -> Any: ...
    @classmethod
    def GetId(cls, classRDKit) -> Any: ...
    @classmethod
    def GetMol(cls, classRDKit) -> Any: ...
    @overload
    @classmethod
    def GetPos(cls, classRDKit, int) -> Any: ...
    @overload
    @classmethod
    def GetPos(cls, classRDKit) -> Any: ...
    @classmethod
    def GetType(cls, classRDKit) -> Any: ...
    @classmethod
    def SetActiveConformer(cls, classRDKit, int) -> Any: ...
    @classmethod
    def __reduce__(cls) -> Any: ...

class MolChemicalFeatureFactory(Boost.Python.instance):
    GetFeaturesForMol: ClassVar[function] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    @classmethod
    def GetFeatureDefs(cls, classRDKit) -> Any: ...
    @classmethod
    def GetFeatureFamilies(cls, classRDKit) -> Any: ...
    @classmethod
    def GetMolFeature(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def GetNumFeatureDefs(cls, classRDKit) -> Any: ...
    @classmethod
    def GetNumMolFeatures(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def __reduce__(cls) -> Any: ...

def BuildFeatureFactory(*args, **kwargs) -> Any: ...
def BuildFeatureFactoryFromString(*args, **kwargs) -> Any: ...
def GetAtomMatch(classboost) -> Any: ...
