from typing import Any

def ComputeConfBox(classRDKit) -> Any: ...
def ComputeConfDimsAndOffset(classRDKit) -> Any: ...
def ComputeUnionBox(*args, **kwargs) -> Any: ...
def EncodeShape(classRDKit, classRDGeom) -> Any: ...
def ShapeProtrudeDist(*args, **kwargs) -> Any: ...
def ShapeTanimotoDist(*args, **kwargs) -> Any: ...
def ShapeTverskyIndex(*args, **kwargs) -> Any: ...
