from typing import Any, ClassVar

import Boost.Python

class TautomerQuery(Boost.Python.instance):
    __safe_for_unpickling__: ClassVar[bool] = ...
    @classmethod
    def __init__(cls, classboost, classRDKit) -> Any: ...
    @classmethod
    def GetModifiedAtoms(cls, classRDKit) -> Any: ...
    @classmethod
    def GetModifiedBonds(cls, classRDKit) -> Any: ...
    @classmethod
    def GetSubstructMatch(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def GetSubstructMatches(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def GetSubstructMatchesWithTautomers(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def GetTautomers(cls, classRDKit) -> Any: ...
    @classmethod
    def GetTemplateMolecule(cls, classRDKit) -> Any: ...
    @classmethod
    def IsSubstructOf(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def PatternFingerprintTemplate(cls, classRDKit) -> Any: ...
    @classmethod
    def ToBinary(cls, classRDKit) -> Any: ...
    @classmethod
    def __getinitargs__(cls, classRDKit) -> Any: ...
    @classmethod
    def __reduce__(cls) -> Any: ...

def PatternFingerprintTautomerTarget(classRDKit) -> Any: ...
def TautomerQueryCanSerialize() -> Any: ...
