from typing import Any

import Boost.Python

class Snapshot(Boost.Python.instance):
    @classmethod
    def __init__(cls, classboost, classRDKit) -> Any: ...
    @classmethod
    def GetEnergy(cls, classRDKit) -> Any: ...
    @classmethod
    def GetPoint2D(cls, classRDKit, unsignedint) -> Any: ...
    @classmethod
    def GetPoint3D(cls, classRDKit, unsignedint) -> Any: ...
    @classmethod
    def SetEnergy(cls, classRDKit, double) -> Any: ...
    @classmethod
    def __reduce__(cls) -> Any: ...

class Trajectory(Boost.Python.instance):
    @classmethod
    def __init__(cls, classboost, classRDKit) -> Any: ...
    @classmethod
    def AddConformersToMol(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def AddSnapshot(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def Clear(cls, classRDKit) -> Any: ...
    @classmethod
    def Dimension(cls, classRDKit) -> Any: ...
    @classmethod
    def GetSnapshot(cls, classRDKit, unsignedint) -> Any: ...
    @classmethod
    def InsertSnapshot(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def NumPoints(cls, classRDKit) -> Any: ...
    @classmethod
    def RemoveSnapshot(cls, classRDKit, unsignedint) -> Any: ...
    @classmethod
    def __len__(cls, classRDKit) -> Any: ...
    @classmethod
    def __reduce__(cls) -> Any: ...

def ReadAmberTrajectory(*args, **kwargs) -> Any: ...
def ReadGromosTrajectory(*args, **kwargs) -> Any: ...
