from _typeshed import Incomplete
from rdkit.ML.Composite import Composite as Composite

class BayesComposite(Composite.Composite):
    resultProbs: Incomplete
    condProbs: Incomplete
    def Train(self, data, verbose: int = ...) -> None: ...
    modelVotes: Incomplete
    def ClassifyExample(self, example, threshold: int = ..., verbose: int = ..., appendExample: int = ...): ...
    def __init__(self) -> None: ...

def CompositeToBayesComposite(obj) -> None: ...
def BayesCompositeToComposite(obj) -> None: ...
