def GetNodeList(cluster): ...
def GetNodesDownToCentroids(cluster, above: int = ...): ...
def FindClusterCentroidFromDists(cluster, dists): ...
def SplitIntoNClusters(cluster, n, breadthFirst: bool = ...): ...
