from _typeshed import Incomplete
from rdkit import DataStructs as DataStructs
from rdkit.VLib.Node import VLibNode as VLibNode

class DbFpSupplier(VLibNode):
    fpCol: Incomplete
    def __init__(self, dbResults, fpColName: str = ..., usePickles: bool = ...) -> None: ...
    def GetColumnNames(self): ...
    def next(self): ...
    __next__: Incomplete

class ForwardDbFpSupplier(DbFpSupplier):
    def __init__(self, *args, **kwargs) -> None: ...
    def reset(self) -> None: ...
    def NextItem(self): ...

class RandomAccessDbFpSupplier(DbFpSupplier):
    def __init__(self, *args, **kwargs) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, idx): ...
    def reset(self) -> None: ...
    def NextItem(self): ...
