from _typeshed import Incomplete
from rdkit import Chem as Chem, DataStructs as DataStructs
from rdkit.Chem import MACCSkeys as MACCSkeys
from rdkit.ML.Cluster import Murtagh as Murtagh

def error(msg) -> None: ...
def message(msg) -> None: ...
def GetRDKFingerprint(mol): ...
def FoldFingerprintToTargetDensity(fp, **fpArgs): ...
def FingerprintMol(mol, fingerprinter=..., **fpArgs): ...
def FingerprintsFromSmiles(dataSource, idCol, smiCol, fingerprinter=..., reportFreq: int = ..., maxMols: int = ..., **fpArgs): ...
def FingerprintsFromMols(mols, fingerprinter=..., reportFreq: int = ..., maxMols: int = ..., **fpArgs): ...
def FingerprintsFromPickles(dataSource, idCol, pklCol, fingerprinter=..., reportFreq: int = ..., maxMols: int = ..., **fpArgs): ...
def FingerprintsFromDetails(details, reportFreq: int = ...): ...

class FingerprinterDetails:
    def __init__(self) -> None: ...
    def GetMetricName(self): ...
    metric: Incomplete
    def SetMetricFromName(self, name) -> None: ...

def Usage() -> None: ...
def ParseArgs(details: Incomplete | None = ...): ...
