from rdkit import DataStructs as DataStructs

class BitClusterer:
    def __init__(self, idList, nCluster, type=...) -> None: ...
    def ClusterBits(self, corrMat) -> None: ...
    def SetClusters(self, clusters) -> None: ...
    def GetClusters(self): ...
    def MapToClusterScores(self, fp): ...
    def MapToClusterFP(self, fp): ...
