[tool.poetry]
name = "substances-importers"
version = "0.1.0"
description = ""
authors = ["Luidgi Gromat <gromat.luidgi@gmail.com>"]
readme = "README.md"
packages = [{include = "substances_importers"}, {include = "substances_importers/py.typed"}]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.28.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
