[tool.poetry]
name = "shared-kernel"
version = "0.1.0"
description = ""
authors = ["Luidgi Gromat <gromat.luidgi@gmail.com>"]
readme = "README.md"
packages = [{include = "shared"}, {include= "shared/py.typed"}]

[tool.poetry.dependencies]
python = "^3.9"
pydantic = "^1.10.2"


[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"
mypy = "^0.991"
black = "^22.12.0"
pylint = "^2.15.8"
bandit = "^1.7.4"
flask = "^2.2.2"
isort = "^5.11.3"
flake8 = "^6.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
