# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sync.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nsync.proto\x12\x05syncs\">\n\x0bListRequest\x12\x0e\n\x06offset\x18\x01 \x01(\x05\x12\r\n\x05limit\x18\x02 \x01(\x05\x12\x10\n\x08ordering\x18\x03 \x03(\t\"\x18\n\nGetRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x1d\n\x0cListResponse\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\",\n\x0cItemResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08provider\x18\x02 \x01(\t2t\n\x05Syncs\x12\x36\n\tListSyncs\x12\x12.syncs.ListRequest\x1a\x13.syncs.ListResponse\"\x00\x12\x33\n\x07GetSync\x12\x11.syncs.GetRequest\x1a\x13.syncs.ItemResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sync_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LISTREQUEST._serialized_start=21
  _LISTREQUEST._serialized_end=83
  _GETREQUEST._serialized_start=85
  _GETREQUEST._serialized_end=109
  _LISTRESPONSE._serialized_start=111
  _LISTRESPONSE._serialized_end=140
  _ITEMRESPONSE._serialized_start=142
  _ITEMRESPONSE._serialized_end=186
  _SYNCS._serialized_start=188
  _SYNCS._serialized_end=304
# @@protoc_insertion_point(module_scope)
