# Lambda Functions
executeSync:
  handler: src/lambdas/syncs/execute_sync/handler.handle
  layers:
    - !Ref PythonRequirementsLambdaLayer
  package:
    individually: true
    exclude:
      - "./**"
    include:
      - ./src/lambdas/syncs/execute_sync/dependencies.py
      - ./src/lambdas/syncs/execute_sync/handler.py
    # Configure EFS
  fileSystemConfig:
    arn: "arn:aws:elasticfilesystem:${aws:region}:${aws:accountId}:access-point/fsap-00444d993db812161"
    localMountPath: "${self:custom.LocalMountPath}"
