from typing import Any, ClassVar

from typing import overload
import Boost.Python

class ContourParams(Boost.Python.instance):
    __instance_size__: ClassVar[int] = ...
    contourWidth: Any
    dashNegative: Any
    extraGridPadding: Any
    fillGrid: Any
    gridResolution: Any
    setScale: Any
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    @classmethod
    def setColourMap(cls, structRDKit, classboost) -> Any: ...
    @classmethod
    def setContourColour(cls, structRDKit, classboost) -> Any: ...
    @classmethod
    def __reduce__(cls) -> Any: ...

class IntStringMap(Boost.Python.instance):
    __instance_size__: ClassVar[int] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    @classmethod
    def __contains__(cls, other) -> Any: ...
    @classmethod
    def __delitem__(cls, other) -> Any: ...
    @classmethod
    def __getitem__(cls, index) -> Any: ...
    @classmethod
    def __iter__(cls) -> Any: ...
    @classmethod
    def __len__(cls) -> Any: ...
    @classmethod
    def __reduce__(cls) -> Any: ...
    @classmethod
    def __setitem__(cls, index, object) -> Any: ...

class MolDraw2D(Boost.Python.instance):
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    @classmethod
    def ClearDrawing(cls, classRDKit) -> Any: ...
    @classmethod
    def DrawArc(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def DrawArrow(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def DrawAttachmentLine(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def DrawEllipse(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def DrawLine(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def DrawMolecule(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def DrawMoleculeWithHighlights(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def DrawMolecules(cls, classRDKit, classboost) -> Any: ...
    @classmethod
    def DrawPolygon(cls, classRDKit, classboost) -> Any: ...
    @classmethod
    def DrawReaction(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def DrawRect(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def DrawString(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def DrawTriangle(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def DrawWavyLine(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def FillPolys(cls, classRDKit) -> Any: ...
    @classmethod
    def FontSize(cls, classRDKit) -> Any: ...
    @overload
    @classmethod
    def GetDrawCoords(cls, classRDKit, classRDGeom) -> Any: ...
    @overload
    @classmethod
    def GetDrawCoords(cls, classRDKit, int) -> Any: ...
    @classmethod
    def Height(cls, classRDKit) -> Any: ...
    @classmethod
    def LineWidth(cls, classRDKit) -> Any: ...
    @classmethod
    def Offset(cls, classRDKit) -> Any: ...
    @classmethod
    def SetColour(cls, classRDKit, classboost) -> Any: ...
    @classmethod
    def SetDrawOptions(cls, classRDKit, structRDKit) -> Any: ...
    @classmethod
    def SetFillPolys(cls, classRDKit, bool) -> Any: ...
    @classmethod
    def SetFontSize(cls, classRDKit, double) -> Any: ...
    @classmethod
    def SetLineWidth(cls, classRDKit, double) -> Any: ...
    @classmethod
    def SetOffset(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def SetScale(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def Width(cls, classRDKit) -> Any: ...
    @classmethod
    def drawOptions(cls, classRDKit) -> Any: ...
    @classmethod
    def __reduce__(cls) -> Any: ...

class MolDraw2DCairo(MolDraw2D):
    __instance_size__: ClassVar[int] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    @classmethod
    def FinishDrawing(cls, classRDKit) -> Any: ...
    @classmethod
    def GetDrawingText(cls, classRDKit) -> Any: ...
    @classmethod
    def WriteDrawingText(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def __reduce__(cls) -> Any: ...

class MolDraw2DSVG(MolDraw2D):
    __instance_size__: ClassVar[int] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    @classmethod
    def AddMoleculeMetadata(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def FinishDrawing(cls, classRDKit) -> Any: ...
    @classmethod
    def GetDrawingText(cls, classRDKit) -> Any: ...
    @classmethod
    def TagAtoms(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def __reduce__(cls) -> Any: ...

class MolDrawOptions(Boost.Python.instance):
    __instance_size__: ClassVar[int] = ...
    addAtomIndices: Any
    addBondIndices: Any
    addStereoAnnotation: Any
    additionalAtomLabelPadding: Any
    annotationFontScale: Any
    atomHighlightsAreCircles: Any
    atomLabelDeuteriumTritium: Any
    atomLabels: Any
    atomRegions: Any
    baseFontSize: Any
    bondLineWidth: Any
    centreMoleculesBeforeDrawing: Any
    circleAtoms: Any
    clearBackground: Any
    comicMode: Any
    continuousHighlight: Any
    drawMolsSameScale: Any
    dummiesAreAttachments: Any
    dummyIsotopeLabels: Any
    explicitMethyl: Any
    fillHighlights: Any
    fixedBondLength: Any
    fixedFontSize: Any
    fixedScale: Any
    flagCloseContactsDist: Any
    fontFile: Any
    highlightBondWidthMultiplier: Any
    highlightRadius: Any
    includeAtomTags: Any
    includeChiralFlagLabel: Any
    includeMetadata: Any
    includeRadicals: Any
    isotopeLabels: Any
    legendFontSize: Any
    legendFraction: Any
    maxFontSize: Any
    minFontSize: Any
    multipleBondOffset: Any
    noAtomLabels: Any
    padding: Any
    prepareMolsBeforeDrawing: Any
    rotate: Any
    scaleBondWidth: Any
    scaleHighlightBondWidth: Any
    scalingFactor: Any
    simplifiedStereoGroupLabel: Any
    singleColourWedgeBonds: Any
    splitBonds: Any
    unspecifiedStereoIsUnknown: Any
    useMolBlockWedging: Any
    variableAtomRadius: Any
    variableBondWidthMultiplier: Any
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    @classmethod
    def getAnnotationColour(cls, structRDKit) -> Any: ...
    @classmethod
    def getBackgroundColour(cls, structRDKit) -> Any: ...
    @classmethod
    def getHighlightColour(cls, structRDKit) -> Any: ...
    @classmethod
    def getLegendColour(cls, structRDKit) -> Any: ...
    @classmethod
    def getSymbolColour(cls, structRDKit) -> Any: ...
    @classmethod
    def getVariableAttachmentColour(cls, structRDKit) -> Any: ...
    @classmethod
    def setAnnotationColour(cls, structRDKit, classboost) -> Any: ...
    @classmethod
    def setAtomPalette(cls, structRDKit, classboost) -> Any: ...
    @classmethod
    def setBackgroundColour(cls, structRDKit, classboost) -> Any: ...
    @classmethod
    def setHighlightColour(cls, structRDKit, classboost) -> Any: ...
    @classmethod
    def setLegendColour(cls, structRDKit, classboost) -> Any: ...
    @classmethod
    def setSymbolColour(cls, structRDKit, classboost) -> Any: ...
    @classmethod
    def setVariableAttachmentColour(cls, structRDKit, classboost) -> Any: ...
    @classmethod
    def updateAtomPalette(cls, structRDKit, classboost) -> Any: ...
    @classmethod
    def useAvalonAtomPalette(cls, structRDKit) -> Any: ...
    @classmethod
    def useBWAtomPalette(cls, structRDKit) -> Any: ...
    @classmethod
    def useCDKAtomPalette(cls, structRDKit) -> Any: ...
    @classmethod
    def useDefaultAtomPalette(cls, structRDKit) -> Any: ...
    @classmethod
    def __reduce__(cls) -> Any: ...

class map_indexing_suite_IntStringMap_entry(Boost.Python.instance):
    __instance_size__: ClassVar[int] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    @classmethod
    def data(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def key(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def __reduce__(cls) -> Any: ...

def ContourAndDrawGaussians(*args, **kwargs) -> Any: ...
def ContourAndDrawGrid(*args, **kwargs) -> Any: ...
def DrawMoleculeACS1996(*args, **kwargs) -> Any: ...
def MeanBondLength(classRDKit) -> Any: ...
def MolToACS1996SVG(classRDKit) -> Any: ...
def MolToSVG(classRDKit) -> Any: ...
def PrepareAndDrawMolecule(*args, **kwargs) -> Any: ...
def PrepareMolForDrawing(classRDKit) -> Any: ...
def SetACS1996Mode(structRDKit, double) -> Any: ...
@overload
def SetDarkMode(structRDKit) -> Any: ...
@overload
def SetDarkMode(classRDKit) -> Any: ...
def SetMonochromeMode(*args, **kwargs) -> Any: ...
def UpdateDrawerParamsFromJSON(*args, **kwargs) -> Any: ...
def UpdateMolDrawOptionsFromJSON(*args, **kwargs) -> Any: ...
