from math import *
from _typeshed import Incomplete
from rdkit import RDConfig as RDConfig

knownMethods: Incomplete

def HAS(strArg, composList, atomDict): ...
def SUM(strArg, composList, atomDict): ...
def MEAN(strArg, composList, atomDict): ...
AVG = MEAN

def DEV(strArg, composList, atomDict): ...
def MIN(strArg, composList, atomDict): ...
def MAX(strArg, composList, atomDict): ...
def CalcSingleCompoundDescriptor(compos, argVect, atomDict, propDict): ...
def CalcMultipleCompoundsDescriptor(composVect, argVect, atomDict, propDictList): ...
